---
notes:
    - "Based on June 2007 laboratory Calibration with BB02 logger"
format_version: "0.99"
stages:
    -
      description : "SENSOR - DPG 5018" 
      DBIRD_response_type : "CALIBRATED" 
      input_units :  {name: "PA", description: "PRESSURE"}
      output_units : {name: "V", description: "VOLTS"}
      calibration_date: "2007"
      gain : 
        value: 4.38e-4
        frequency: 1
      filter:
        type : "PolesZeros"
        units: "rad/s"
        zeros :
            - 0.0, 0.0
        poles :
            - -0.0138, 0.000
