---
# Copied from DPG 5004 calibration
stages:
    -
      description : "SENSOR - GENERIC DPG" # optionel
      DBIRD_response_type : "THEORETICAL" # optionel
      input_units :  {name: "PA", description: "PRESSURE"}
      output_units : {name: "V", description: "VOLTS"}
      gain : 
        value: 4.25e-4
        frequency: 1.
      response:
        type : "PolesZeros"
        include: "sensor/include/SIO-LDEO#DPG#generic#.pz.rad.yaml"
