---
format_version: "0.107"
revision: 
    date: "2017-11-30"
    authors: 
        -
            first_name: "Wayne"
            last_name: "Crawford"
            email: "crawford@ipgp.fr"
$ref_dir: 'responses/'
sensor:
    notes: 
        - "dip value of 90 assumes positive output = pressure decrease (seafloor down => pressure up)"
    equipment:
        model: "HTI-04-PLC-ULF"
        type: "Hydrophone"
        description: "HiTech HTI-04-PLC-ULF hydrophone, 0.01-XXX Hz"
        manufacturer: "HiTech, inc"
        vendor: "various"
    seed_codes:
        band_base: "B"
        instrument: "D"
        orientation:
            "H": {azimuth.deg: [0,0], dip.deg: [90,0]}
    response_stages:
        - $ref: "HiTech_HTI-04-PLC-ULF_voltage-mode_theoretical.response.yaml#response"
